[workspace]
resolver = "3"
members = ["kernel"]

[package]
name = "rust-os-runner"
version = "0.1.0"
edition = "2024"
publish = false

[build-dependencies]
bootloader = { version = "=0.11.17", default-features = false, features = [
  "bios",
] }
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
